apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 15m

  values:
    persistentVolumeClaim:
      enabled: true

    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: 192.168.111.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    serviceDns:
      type: LoadBalancer
      loadBalancerIP: 192.168.111.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
