apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pihole-healthcheck
  namespace: pihole
spec:
  podSelector:
    matchLabels:
      app: pihole
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 31622
