apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: immich-redis
      namespace: immich
  values:
    image:
      tag: v2.0.0

    valkey:
      enabled: false
    postgresql:
      enabled: false

    server:
      env:
        DB_URL: "postgresql://immich:$(DB_PASSWORD)@database:5432/immich"
        REDIS_URL: "ioredis://immich-valkey:6379"
      envFrom:
        - secretRef:
            name: immich-db-app

    microservices:
      env:
        DB_URL: "postgresql://immich:$(DB_PASSWORD)@database:5432/immich"
        REDIS_URL: "ioredis://immich-valkey:6379"
      envFrom:
        - secretRef:
            name: immich-db-app

    immich:
      persistence:
        library:
          enabled: true
          existingClaim: immich-library-pvc
    
