apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: "18.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: public.ecr.aws
      repository: bitnami/redis
      tag: "8.6.1"

    auth:
      enabled: false
    
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
