apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.10.x"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: immich-redis
      namespace: immich
  values:
    image:
      tag: v2.0.0

    valkey:
      enabled: false
    postgresql:
      enabled: false

    server:
      env:
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: immich-db-superuser
              key: password
        
        DB_USERNAME: "postgres"
        
        # 3. Connection Details
        DB_HOSTNAME: "database"
        DB_DATABASE_NAME: "immich"
        REDIS_URL: "ioredis://immich-valkey:6379"

    microservices:
      env:
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: immich-db-superuser
              key: password
        
        DB_USERNAME: "postgres"
        
        DB_HOSTNAME: "database"
        DB_DATABASE_NAME: "immich"
        REDIS_URL: "ioredis://immich-valkey:6379"

    immich:
      persistence:
        library:
          enabled: true
          existingClaim: immich-library-pvc
    
