apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
    - name: immich-redis
      namespace: immich
  values:
    image:
      tag: v1.124.0

    env:
      DB_HOSTNAME: immich-db-rw
      DB_DATABASE_NAME: immich
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password

      REDIS_HOSTNAME: immich-redis-master
      REDIS_PORT: "6379"

    immich:
      persistence:
        library:
          enabled: true
          existingClaim: immich-library-pvc

    machine-learning:
      enabled: false
