apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 2

  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
  
  storage:
    size: 20Gi
    storageClass: longhorn
  
  postgresql:
    parameters:
      shared_preload_libraries: "vectors.so"
      search_path: '"$user", public, vectors'

  bootstrap:
    initdb:
      database: immich
      owner: immich

