apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
  
  storage:
    size: 20Gi
    storageClass: longhorn

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    
    parameters:
      search_path: '"$user", public, vectors'

  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
