# ./clusters/my-cluster/metallb/metallb-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.7"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    speaker:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

    extraObjects:
      - apiVersion: v1
        kind: Service
        metadata:
          name: metallb-speaker
          namespace: metallb-system
        spec:
          selector:
            app.kubernetes.io/component: speaker
            app.kubernetes.io/instance: metallb
            app.kubernetes.io/name: metallb
          ports:
            - name: memberlist
              port: 7946
              protocol: TCP
              targetPort: 7946
      - apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-metallb-speaker
          namespace: metallb-system
        spec:
          podSelector:
            matchLabels:
              app.kubernetes.io/component: speaker
          ingress:
            - from:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/component: speaker
              ports:
                - port: 7946
                  protocol: TCP
