apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: monitoring
stringData:
    token: ENC[AES256_GCM,data:+Vsbtw8PsrdgRMj+PkDhrsgLwDDEjWHnB/dSghf8xodjxCNHmJXuuEWW+eUPHGJk8DxwbY1EVhcLSZWkXeARJHWoJ6cwo//409pYU7U5rw/41ELutPGBT9xq+2aIvzP2Vq9EYbkKMK3fwhXWWDvf5XBtLXmqphN7etkOX8rgDo8e3QSllTMmmJaa0CnrsmWFV9Zl/tstOPimQV4zRBAwiAmTVhpqNzNczORqpbTTFU+7Txq7m1hl,iv:2YDr1UbtAMAsyPk8ODuX7M6zX78XixFYVLsC2dZ9FMY=,tag:pcUIWRxpm+Z4SuJzWLAgtA==,type:str]
sops:
    age:
        - recipient: age1vtxcsnvdcj33tk2r8u6m7j947fv5m4gvmyw538ve873km84gf5vql65e6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwREhrNDkwV3M4aVBORHdx
            bWlLWW91TjFYdFZHOERXSjZrNERxTU90Z0drCnFPKzRNaUVDYWdmZ21yZ3VnVmd2
            L1R1T2J5Y1BqYWxlZTI1TkdPWHU4UDAKLS0tIDFzRi9nRWtzSVhtMk13aXc0SnV3
            S28rME9TdjVIMDY4QXJpbTg5M1RyUjgKNmPudvASgRMTV0T4BgALwVCy/Qe+URN8
            H0KETMqfkSbrdlajiGYijVkoa9vRglDQBAt0fL2eEYf64N6gB0WSuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T22:09:58Z"
    mac: ENC[AES256_GCM,data:Eu+hMlZFUVArYB66eWUw2r/0FOZM1whuAdvuruAz7iXAltH7KjuzP3Gd42Uy22A8np9JymSId8RNdRrpmpEOkXHhymvW2gdxeZj4G/7Mb+fQ7zK6kQ7oc9DQIa7SEgocp0HaxT721M3v1vtWZiOKHT4YmrdC0ArnrUKg76DB2P8=,iv:+lVhXl4aeoWO5JDEkuEEgfokBE9asgaS1iBjkr0jn1Q=,tag:aBqyeyeR7jOvg8kxdHpjKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
