# monitoring/unpoller-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: unpoller
      version: "v2.11.2-Chart6"
      sourceRef:
        kind: HelmRepository
        name: unpoller
        namespace: monitoring
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PodMonitor
              name: unifi-poller
            patch: |
              - op: add
                path: /metadata/labels/release
                value: prometheus-stack
  values:
    dashboards:
      create: false
      grafana:
        create: false
    unifi:
      controller:
        url: "https://router.seanzhong.com"
      auth:
        existingSecret:
          name: unpoller-credentials
          userKey: UNPOLLER_UNIFI_USER
          passKey: UNPOLLER_UNIFI_PASS
    prometheus:
      podMonitor:
        enabled: true
        endpoint:
          port: 9130
