---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
spec:
  ingressClassName: traefik
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.seanzhong.com`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    secretName: portainer-certificate-secret
