---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 30m
  chart:
    spec:
      chart: portainer
      version: "2.33.1"
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
      interval: 5m
  releaseName: portainer
  targetNamespace: portainer
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
    ingress:
      enabled: false

