apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-ingressroute-certificate
  namespace: portainer
spec:
  secretName: portainer-certificate-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - portainer.seanzhong.com

