# networking/traefik-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "27.0.2"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: networking
  values:
    service:
      type: LoadBalancer

    # This enables the Traefik dashboard
    dashboard:
      enabled: true
      ingressRoute: true

    ingressRoutes:
      - name: traefik-dashboard
        entryPoints:
          - web
        routes:
          - match: Host(`traefik.seanzhong.com`)
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
