---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-tls-secret
  dnsNames:
    - "longhorn.seanzhong.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

