---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 1h
  url: https://kube-vip.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-vip
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  values:
    installAsDaemonset: true
    
    env:
      svc_enable: "true"
      cp_enable: "false"
      vip_interface: "eth0"
      vip_leaderelection: "true"
      vip_address: "192.168.111.20"
      ipam_range: "192.168.111.240-192.168.111.250"

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
