---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 1h
  url: https://kube-vip.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-vip
      version: "0.9.1"
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  values:
    env:
      vip_interface: ""
      vip_arp: "true"
      lb_enable: "true"
      lb_port: "6443"
      vip_subnet: "32"
      cp_enable: "false"
      svc_enable: "true"
      svc_election: "false"

    service:
      enabled: true

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
