apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-vip-cloud-provider
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
    #   - name: KUBEVIP_ENABLE_LOADBALANCERCLASS
    #     value: "true"
    image:
      repository: ghcr.io/kube-vip/kube-vip-cloud-provider
