---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 1h
  url: https://kube-vip.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-vip
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  values:
    installAsDaemonset: true

    config:
      interface: eth0
      leaderElection: true
      enableControlPlane: false
      enableServices: true
      address: 192.168.111.20

    services:
      enabled: true
      loadBalancerIPPool:
        enabled: true
        ipam:
          range: 192.168.111.240-192.168.111.250

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
