apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-install
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/apps/metallb-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m

