---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: szhrune@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: szhrune@gmail.com
            apiTokenSecretRef: 
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "seanzhong.com"
