apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-vip
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  values:
    daemonset:
      enabled: true
    
    config:
      interface: eth0

    services:
      enabled: true
