# networking/traefik-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "37.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: networking
  values:
    service:
      type: LoadBalancer
      spec:
        loadBalancerIp: "192.168.111.250"

    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true

    ingressClass:
      name: traefik
    providers:
      kubernetesCRD:
        ingressClass: traefik
      kubernetesIngress:
        ingressClass: traefik

    ingressRoutes:
      dashboard:
        enabled: false

    rbac:
      namespaced: true
